apiVersion: "v1"
name: cluster-api
description: "Helm chart for cluster api."
home: "https://github.com/giantswarm/cluster-api-app"
version: "[[ .Version ]]"
appVersion: [[ .AppVersion ]]
annotations:
  application.giantswarm.io/owners: |
    - catalog: default
      provider: aws
      team: firecracker
    - catalog: default
      provider: azure
      team: celestial
  config.giantswarm.io/version: 1.x.x
