apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "labels.common.core" . | nindent 4 }}
  name: {{ include "resource.core.name" . }}-cert
  namespace: {{ include "resource.default.namespace" . }}
spec:
  dnsNames:
  - {{ include "resource.core.name" . }}.{{ include "resource.default.namespace" . }}.svc
  - {{ include "resource.core.name" . }}.{{ include "resource.default.namespace" . }}.svc.cluster.local
  - {{ include "resource.bootstrap.name" . }}.{{ include "resource.default.namespace" . }}.svc
  - {{ include "resource.bootstrap.name" . }}.{{ include "resource.default.namespace" . }}.svc.cluster.local
  - {{ include "resource.controlplane.name" . }}.{{ include "resource.default.namespace" . }}.svc
  - {{ include "resource.controlplane.name" . }}.{{ include "resource.default.namespace" . }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: {{ include "resource.core.name" . }}-cert
