apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.common.core" . | nindent 4 }}
  name: {{ include "resource.core.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.core.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "resource.core.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
