apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.core.name" . }}-cert
  creationTimestamp: null
  labels:
    {{- include "labels.common.core" . | nindent 4 }}
  name: {{ include "resource.core.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-cluster
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cluster.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-clusterclass
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.clusterclass.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterclasses
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-machine
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machine.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-machinedeployment
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machinedeployment.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinedeployments
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-machinehealthcheck
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machinehealthcheck.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinehealthchecks
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-machineset
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machineset.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinesets
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-cluster-x-k8s-io-v1alpha4-machinepool
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machinepool.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.core.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-addons-cluster-x-k8s-io-v1alpha4-clusterresourceset
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.clusterresourceset.addons.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterresourcesets
  sideEffects: None
