apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capi-kubeadm-control-plane-serving-cert'
    controller-gen.kubebuilder.io/version: v0.8.0
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: control-plane-kubeadm
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha4
    cluster.x-k8s.io/v1beta1: v1beta1
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
    helm.sh/chart: cluster-api
  name: kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: Cg==
        service:
          name: capi-kubeadm-control-plane-webhook-service
          namespace: '{{ .Release.Namespace }}'
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
  group: controlplane.cluster.x-k8s.io
  names:
    categories:
      - cluster-api
    kind: KubeadmControlPlane
    listKind: KubeadmControlPlaneList
    plural: kubeadmcontrolplanes
    shortNames:
      - kcp
    singular: kubeadmcontrolplane
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: This denotes whether or not the control plane has the uploaded kubeadm-config configmap
          jsonPath: .status.initialized
          name: Initialized
          type: boolean
        - description: KubeadmControlPlane API Server is ready to receive requests
          jsonPath: .status.ready
          name: API Server Available
          type: boolean
        - description: Kubernetes version associated with this control plane
          jsonPath: .spec.version
          name: Version
          type: string
        - description: Total number of non-terminated machines targeted by this control plane
          jsonPath: .status.replicas
          name: Replicas
          type: integer
        - description: Total number of fully running and ready control plane machines
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: Total number of non-terminated machines targeted by this control plane that have the desired template spec
          jsonPath: .status.updatedReplicas
          name: Updated
          type: integer
        - description: Total number of unavailable machines targeted by this control plane
          jsonPath: .status.unavailableReplicas
          name: Unavailable
          type: integer
      name: v1alpha3
      schema: {}
      served: true
      storage: false
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
        status: {}
    - additionalPrinterColumns:
        - description: Time duration since creation of KubeadmControlPlane
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - description: This denotes whether or not the control plane has the uploaded kubeadm-config configmap
          jsonPath: .status.initialized
          name: Initialized
          type: boolean
        - description: KubeadmControlPlane API Server is ready to receive requests
          jsonPath: .status.ready
          name: API Server Available
          type: boolean
        - description: Kubernetes version associated with this control plane
          jsonPath: .spec.version
          name: Version
          type: string
        - description: Total number of non-terminated machines targeted by this control plane
          jsonPath: .status.replicas
          name: Replicas
          type: integer
        - description: Total number of fully running and ready control plane machines
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: Total number of non-terminated machines targeted by this control plane that have the desired template spec
          jsonPath: .status.updatedReplicas
          name: Updated
          type: integer
        - description: Total number of unavailable machines targeted by this control plane
          jsonPath: .status.unavailableReplicas
          name: Unavailable
          type: integer
      name: v1alpha4
      schema: {}
      served: true
      storage: false
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
        status: {}
    - additionalPrinterColumns:
        - description: Cluster
          jsonPath: .metadata.labels['cluster\.x-k8s\.io/cluster-name']
          name: Cluster
          type: string
        - description: This denotes whether or not the control plane has the uploaded kubeadm-config configmap
          jsonPath: .status.initialized
          name: Initialized
          type: boolean
        - description: KubeadmControlPlane API Server is ready to receive requests
          jsonPath: .status.ready
          name: API Server Available
          type: boolean
        - description: Total number of non-terminated machines targeted by this control plane
          jsonPath: .status.replicas
          name: Replicas
          type: integer
        - description: Total number of fully running and ready control plane machines
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: Total number of non-terminated machines targeted by this control plane that have the desired template spec
          jsonPath: .status.updatedReplicas
          name: Updated
          type: integer
        - description: Total number of unavailable machines targeted by this control plane
          jsonPath: .status.unavailableReplicas
          name: Unavailable
          type: integer
        - description: Time duration since creation of KubeadmControlPlane
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - description: Kubernetes version associated with this control plane
          jsonPath: .spec.version
          name: Version
          type: string
      name: v1beta1
      schema: {}
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
