apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.controlplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common.controlplane" . | nindent 4 }}
