apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-port: "{{ .Values.ports.metrics }}"
  labels:
    {{- include "labels.common.controlplane" . | nindent 4 }}
  name: {{ include "resource.controlplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics }}
    protocol: TCP
    targetPort: metrics
  - name: webhook
    port: {{ .Values.ports.webhook }}
    protocol: TCP
    targetPort: webhook
  selector:
    {{- include "labels.selector.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
