apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.core.name" . }}-cert
  labels:
    {{- include "labels.common.controlplane" . | nindent 4 }}
  name: zzz-{{ include "resource.controlplane.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.controlplane.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-controlplane-cluster-x-k8s-io-v1alpha4-kubeadmcontrolplane
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeadmcontrolplanes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.core.name" . }}-cert
  labels:
    {{- include "labels.common.controlplane" . | nindent 4 }}
  name: {{ include "resource.controlplane.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.controlplane.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha4-kubeadmcontrolplane
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeadmcontrolplanes
  sideEffects: None
